add protos for info-service and app-lcm
openinfradev/tks-proto pull request #2
Opened 2021-04-12 06:50 UTC by intelliguy

pr#1 proto-lint가 merge된 이후 pr완료예정입니다.

2021-04-12 07:41 UTC, jabbukka commented
lint의 rule 중 comments 관련은 go comments 스타일을 따르게 되어있습니다. 
go comments style은 해당 필드/메서드의 상단에 주석을 달아야하고, `// RpcMethod `로 시작해야합니다.

2021-04-12 08:35 UTC, seungkyua commented on protos/info.proto
> +  bool uniqueness = 3;// uniqueness for requested label
코멘트 때문에 lint 에러 나는 것 같네요.

2021-04-12 08:36 UTC, seungkyua commented on protos/common.proto
> +  repeated Cluster clusters = 4;  // array of Cluster Info
코멘트 때문에 lint 에러 나는 것 같네요.

2021-04-12 08:57 UTC, intelliguy commented on protos/info.proto
> +  bool uniqueness = 3;// uniqueness for requested label
열심히 고치는 중...
도끼자루 썩어나가는 시간이 걸리네요... ㅜ,.ㅜ

2021-04-13 00:45 UTC, jabbukka requested changes

2021-04-13 00:45 UTC, jabbukka commented on protos/application_lcm.proto
> +  Define messages to create new info to TKS-Info service.
주석 내용이 TKS-info로 잘못 작성된 것 같습니다.

2021-04-13 00:45 UTC, jabbukka commented on protos/common.proto
> +  EpType type = 0;
messege field number는 1부터 시작합니다

2021-04-13 00:45 UTC, jabbukka commented on protos/common.proto
> +  string app_id = 0;
여기도 1부터 시작하도록 변경해야합니다.

2021-04-13 00:45 UTC, jabbukka commented on protos/info.proto
> +  string cluster_id = 2;
field number 1, 2로 변경해주세요~

2021-04-13 00:45 UTC, jabbukka commented on protos/info.proto
> +  repeated Endpoint endpoints = 6;
field number 3으로 ..

2021-04-13 00:45 UTC, jabbukka commented on protos/common.proto
> +  string name = 1;
field number 2로 변경해주세요~

2021-04-13 01:52 UTC, intelliguy commented
이제부터 리뷰 부탁드려요....

2021-04-13 04:41 UTC, jabbukka approved these changes

2021-04-13 04:44 UTC, merged