refactor info.proto
openinfradev/tks-proto pull request #5
Opened 2021-04-15 02:08 UTC by jabbukka

* 재논의된 tks의 데이터 구조에 의해 Mc-ops를 없애고 tenant로 관리하도록 변경

2021-04-15 04:07 UTC, intelliguy commented on protos/common.proto
> -message McInfo {
Tenant와 관련된 기록은 따로 하지않고 그냥 set of cluster만 있는 건가요?
예를 들어 tenant 생성시점을 보려면 내부 전체 클러스터의 모든 created_ts를 살펴보고 가장 오래된걸로 유추한다든지?

2021-04-15 04:20 UTC, jabbukka commented on protos/common.proto
> -message McInfo {
Tenant에 대한 기록은 Database에는 할텐데 message로 tenant 를 가져오는 경우는 없지 않을까 해서 message Tenant는 만들지 않았습니다. rpc 에도 GetTenant 는 만들지 않고 GetTenantID, GetTenantAuth만 넣어놨는데 GetTenant가 필요할까요?

2021-04-16 01:39 UTC, zugwan requested changes

2021-04-16 01:39 UTC, zugwan commented on protos/info.proto
> +  rpc GetTenantAuth(IDRequest) returns (GetTenantAuthResponse) {}
코드 자체에 대한 의견은 아니지만 싱크 미팅 때 문의 드렸던 DB에 저장된 정보를 얻기 위한 정책과 관련해서 정리를 했으면 합니다.
auth 정보를 얻기 위해 1) Info 서비스를 통한다, 2) DB에 직접 접근하여 tenant_id로 조회해서 가져온다 중 1번을 사용하는 것으로 이해가 되는데 (이 부분은 저도 동의합니다) 각 DB 테이블과 서비스 별로 소유자를 정리하는 것이 좋을 듯 합니다.

2021-04-16 01:39 UTC, zugwan commented on protos/info.proto
> +  string tenant_id = 2;
하나의 계약에 여러 개의 IaasS가 사용될 수 있으니 contract_id는 빼고 tenant_id만 mandatory로 하는 것이 좋지 않을까 의견 드립니다.

2021-04-16 01:39 UTC, zugwan commented on protos/common.proto
> -message McInfo {
> 
> 
> Tenant와 관련된 기록은 따로 하지않고 그냥 set of cluster만 있는 건가요?
> 예를 들어 tenant 생성시점을 보려면 내부 전체 클러스터의 모든 created_ts를 살펴보고 가장 오래된걸로 유추한다든지?

tenant가 여러 IaaS 에 접근하기 위한 인증 정보만을 담고 있는데 생성 시점 등을 관리해야할 이유가 있나요?

2021-04-16 01:57 UTC, jabbukka commented on protos/info.proto
> +  rpc GetTenantAuth(IDRequest) returns (GetTenantAuthResponse) {}
구두로 말씀드린 것과 같이 각 DB Table에 대한 읽기/쓰기 등의 모든 접근은 소유자만 하는 것으로 정해야할 것 같습니다.
예를 들어 contracts table은 TKS-Info에서는 직접 조회하지 않아야하고, clusters table을 TKS-contract가 조회하지 않아야 합니다.

2021-04-16 01:59 UTC, jabbukka commented on protos/info.proto
> +  string tenant_id = 2;
네 contract_id로 가져오는 경우는 array로 리턴을 해야겠네요.

2021-04-16 02:15 UTC, zugwan approved these changes

2021-04-16 04:43 UTC, merged