Add AddApp, UpdateApp, DeleteApp func
openinfradev/tks-proto pull request #9
Opened 2021-04-21 08:51 UTC by seungkyua

아래 function 을 추가했음
- [ ] AddApp
- [ ] UpdateApp
- [ ] DeleteApp

2021-04-21 10:11 UTC, intelliguy requested changes, later dismissed

2021-04-21 10:11 UTC, intelliguy commented on protos/info.proto
> +  // DeleteApp create new app info.
DeleteApp delete new app info.

2021-04-21 10:11 UTC, intelliguy commented on protos/info.proto
> +  // UpdateApp updates an app info.
전체를 넣어주고 통으로 바꿔주는 것 같은데 PutApp이 더 좋을꺼 같은데요.. (그냥 의견입니다.)

2021-04-22 00:38 UTC, seungkyua commented on protos/info.proto
> +  // UpdateApp updates an app info.
contract 과 csp info 도 update 로 되어 있어서 용어를 통일했어요.

2021-04-22 00:46 UTC, seungkyua commented on protos/info.proto
> +  // DeleteApp create new app info.
앗. 그렇네요.

2021-04-22 03:07 UTC, jabbukka commented on protos/info.proto
> +  string cluster_id = 1;
app_id로 업데이트 하는 것이 아닌가요?

2021-04-22 03:08 UTC, jabbukka commented on protos/info.proto
> +  string cluster_id = 1;
app을 삭제할때 cluster_id를 넘겨줘야할까요? (app_id가 고유한 id라고 가정한다면)

2021-04-22 03:14 UTC, seungkyua commented on protos/info.proto
> +  string cluster_id = 1;
cluster_id 는 app_id 가 uuid 이긴 하지만 혹지 모를 조건으로 특정 cluster 를 지정하기 위해서 추가한 것이고, app_id 는 ServiceApp 에 포함되어 있습니다.

2021-04-22 03:15 UTC, seungkyua commented on protos/info.proto
> +  string cluster_id = 1;
cluster_id 는 app_id 가 uuid 이긴 하지만 혹지 모를 조건으로 특정 cluster 를 지정하기 위해서 추가한 것입니다.

2021-04-22 03:20 UTC, jabbukka approved these changes

2021-04-22 05:49 UTC, merged